In [1]:
import psycopg2
import pandas as pd

In [2]:
DBNAME = "opportunity_youth"

In [3]:
conn = psycopg2.connect(dbname=DBNAME)

In [4]:
pums_2017 = pd.read_sql("SELECT * FROM pums_2017 LIMIT 10;", conn)
print(pd.read_sql("SELECT count(*) FROM pums_2017;", conn), list(pums_2017.columns), sep='\n\n')
pums_2017

    count
0  359075

['rt', 'serialno', 'division', 'sporder', 'puma', 'region', 'st', 'adjinc', 'pwgtp', 'agep', 'cit', 'citwp', 'cow', 'ddrs', 'dear', 'deye', 'dout', 'dphy', 'drat', 'dratx', 'drem', 'eng', 'fer', 'gcl', 'gcm', 'gcr', 'hins1', 'hins2', 'hins3', 'hins4', 'hins5', 'hins6', 'hins7', 'intp', 'jwmnp', 'jwrip', 'jwtr', 'lanx', 'mar', 'marhd', 'marhm', 'marht', 'marhw', 'marhyp', 'mig', 'mil', 'mlpa', 'mlpb', 'mlpcd', 'mlpe', 'mlpfg', 'mlph', 'mlpi', 'mlpj', 'mlpk', 'nwab', 'nwav', 'nwla', 'nwlk', 'nwre', 'oip', 'pap', 'relp', 'retp', 'sch', 'schg', 'schl', 'semp', 'sex', 'ssip', 'ssp', 'wagp', 'wkhp', 'wkl', 'wkw', 'wrk', 'yoep', 'anc', 'anc1p', 'anc2p', 'decade', 'dis', 'drivesp', 'esp', 'esr', 'fod1p', 'fod2p', 'hicov', 'hisp', 'indp', 'jwap', 'jwdp', 'lanp', 'migpuma', 'migsp', 'msp', 'naicsp', 'nativity', 'nop', 'oc', 'occp', 'paoc', 'pernp', 'pincp', 'pobp', 'povpip', 'powpuma', 'powsp', 'privcov', 'pubcov', 'qtrbir', 'rac1p', 'rac2p', 'rac3p', 'racaian', 'racasn', 'r

rt       serialno division sporder   puma region  st   adjinc  pwgtp  agep  \
0  P  2013000019658        9      01  11507      4  53  1061971   15.0  34.0   
1  P  2013000019658        9      02  11507      4  53  1061971   12.0  38.0   
2  P  2013000019658        9      03  11507      4  53  1061971   14.0   4.0   
3  P  2013000019658        9      04  11507      4  53  1061971   12.0   2.0   
4  P  2013000019665        9      01  11601      4  53  1061971   85.0  31.0   
5  P  2013000019665        9      02  11601      4  53  1061971   89.0  29.0   
6  P  2013000019665        9      03  11601      4  53  1061971   88.0  27.0   
7  P  2013000019689        9      01  11608      4  53  1061971   17.0  69.0   
8  P  2013000019689        9      02  11608      4  53  1061971   22.0  58.0   
9  P  2013000019725        9      01  10200      4  53  1061971    3.0  71.0   

   ...  pwgtp71  pwgtp72 pwgtp73 pwgtp74 pwgtp75 pwgtp76 pwgtp77 pwgtp78  \
0  ...     15.0      4.0    14.0     4.0    24.0    15.0     3.0     4.0   
1  ...     13.0      4.0    13.0     4.0    19.0    13.0     3.0     4.0   
2  ...     15.0      4.0    13.0     5.0    27.0    17.0     4.0     5.0   
3  ...     13.0      4.0    13.0     3.0    20.0    13.0     4.0     4.0   
4  ...     94.0     27.0   151.0    26.0    81.0    86.0    92.0    89.0   
5  ...     87.0     27.0   142.0    29.0    89.0    83.0   106.0    81.0   
6  ...     87.0     26.0   142.0    29.0    89.0    82.0   106.0    81.0   
7  ...     29.0      5.0    18.0     4.0     5.0    18.0    18.0    18.0   
8  ...     38.0      5.0    19.0     7.0     7.0    22.0    20.0    20.0   
9  ...      3.0      1.0     1.0     5.0     4.0     4.0     3.0     5.0   

  pwgtp79 pwgtp80  
0    15.0    15.0  
1    11.0    12.0  
2    14.0    15.0  
3    11.0    12.0  
4    89.0    86.0  
5    90.0    78.0  
6    91.0    78.0  
7    18.0     5.0  
8    21.0     6.0  
9     3.0     7.0  

[10 rows x 286 columns]

In [5]:
wa_jobs_2017 = pd.read_sql("SELECT * FROM wa_jobs_2017 LIMIT 10;", conn)
print(print(pd.read_sql("SELECT COUNT(*) FROM wa_jobs_2017;", conn)),  list(wa_jobs_2017.columns), sep="\n\n")
wa_jobs_2017

   count
0  50890
None

['w_geocode', 'c000', 'ca01', 'ca02', 'ca03', 'ce01', 'ce02', 'ce03', 'cns01', 'cns02', 'cns03', 'cns04', 'cns05', 'cns06', 'cns07', 'cns08', 'cns09', 'cns10', 'cns11', 'cns12', 'cns13', 'cns14', 'cns15', 'cns16', 'cns17', 'cns18', 'cns19', 'cns20', 'cr01', 'cr02', 'cr03', 'cr04', 'cr05', 'cr07', 'ct01', 'ct02', 'cd01', 'cd02', 'cd03', 'cd04', 'cs01', 'cs02', 'cfa01', 'cfa02', 'cfa03', 'cfa04', 'cfa05', 'cfs01', 'cfs02', 'cfs03', 'cfs04', 'cfs05', 'createdate']


w_geocode  c000  ca01  ca02  ca03  ce01  ce02  ce03  cns01  cns02  \
0  530019501001010     1     0     1     0     1     0     0      0      0   
1  530019501001024     1     0     1     0     0     0     1      1      0   
2  530019501001026     1     1     0     0     0     1     0      1      0   
3  530019501001044     1     0     1     0     0     1     0      1      0   
4  530019501001053     2     0     2     0     0     0     2      0      0   
5  530019501001061     7     1     3     3     0     5     2      7      0   
6  530019501001090     2     0     2     0     0     2     0      2      0   
7  530019501001099     1     1     0     0     0     1     0      1      0   
8  530019501001104     1     0     0     1     0     0     1      1      0   
9  530019501001112     4     1     2     1     0     2     2      4      0   

   ...  cfa02  cfa03  cfa04  cfa05  cfs01  cfs02  cfs03  cfs04  cfs05  \
0  ...      0      0      0      0      0      0      0      0      0   
1  ...      0      0      0      0      0      0      0      0      0   
2  ...      0      0      0      0      0      0      0      0      0   
3  ...      0      0      0      0      0      0      0      0      0   
4  ...      0      0      0      0      0      0      0      0      0   
5  ...      0      0      0      0      0      0      0      0      0   
6  ...      0      0      0      0      0      0      0      0      0   
7  ...      0      0      0      0      0      0      0      0      0   
8  ...      0      0      0      0      0      0      0      0      0   
9  ...      0      0      0      0      0      0      0      0      0   

   createdate  
0  2019-08-25  
1  2019-08-25  
2  2019-08-25  
3  2019-08-25  
4  2019-08-25  
5  2019-08-25  
6  2019-08-25  
7  2019-08-25  
8  2019-08-25  
9  2019-08-25  

[10 rows x 53 columns]

In [6]:
wa_geo_xwalk = pd.read_sql("SELECT * FROM wa_geo_xwalk LIMIT 10;", conn)
print(print(pd.read_sql("SELECT COUNT(*) FROM wa_geo_xwalk;", conn)),  list(wa_geo_xwalk.columns), sep="\n\n")

wa_geo_xwalk

    count
0  195574
None

['tabblk2010', 'st', 'stusps', 'stname', 'cty', 'ctyname', 'trct', 'trctname', 'bgrp', 'bgrpname', 'cbsa', 'cbsaname', 'zcta', 'zctaname', 'stplc', 'stplcname', 'ctycsub', 'ctycsubname', 'stcd116', 'stcd116name', 'stsldl', 'stsldlname', 'stsldu', 'stslduname', 'stschool', 'stschoolname', 'stsecon', 'dtseconname', 'trib', 'tribname', 'tsub', 'tsubname', 'stanrc', 'stanrcname', 'necta', 'nectname', 'mil', 'milname', 'stwib', 'stwibname', 'blklatdd', 'blklondd', 'createdate']


tabblk2010  st stusps  \
0  530150003001040  53     WA   
1  530150005023015  53     WA   
2  530150021002050  53     WA   
3  530150010001017  53     WA   
4  530150003001005  53     WA   
5  530150003001010  53     WA   
6  530150003001007  53     WA   
7  530150007031027  53     WA   
8  530150012002001  53     WA   
9  530150013002019  53     WA   

                                              stname    cty  \
0  Washington                                    ...  53015   
1  Washington                                    ...  53015   
2  Washington                                    ...  53015   
3  Washington                                    ...  53015   
4  Washington                                    ...  53015   
5  Washington                                    ...  53015   
6  Washington                                    ...  53015   
7  Washington                                    ...  53015   
8  Washington                                    ...  53015   
9  Washington                                    ...  53015   

                                             ctyname         trct  \
0  Cowlitz County, WA                            ...  53015000300   
1  Cowlitz County, WA                            ...  53015000502   
2  Cowlitz County, WA                            ...  53015002100   
3  Cowlitz County, WA                            ...  53015001000   
4  Cowlitz County, WA                            ...  53015000300   
5  Cowlitz County, WA                            ...  53015000300   
6  Cowlitz County, WA                            ...  53015000300   
7  Cowlitz County, WA                            ...  53015000703   
8  Cowlitz County, WA                            ...  53015001200   
9  Cowlitz County, WA                            ...  53015000800   

                                            trctname          bgrp  \
0  3 (Cowlitz, WA)                               ...  530150003001   
1  5.02 (Cowlitz, WA)                            ...  530150005023   
2  21 (Cowlitz, WA)                              ...  530150021002   
3  10 (Cowlitz, WA)                              ...  530150010001   
4  3 (Cowlitz, WA)                               ...  530150003001   
5  3 (Cowlitz, WA)                               ...  530150003001   
6  3 (Cowlitz, WA)                               ...  530150003001   
7  7.03 (Cowlitz, WA)                            ...  530150007031   
8  12 (Cowlitz, WA)                              ...  530150012002   
9  8 (Cowlitz, WA)                               ...  530150008006   

                                            bgrpname  ... stanrcname  necta  \
0  1 (Tract 3, Cowlitz, WA)                      ...  ...       None  99999   
1  3 (Tract 5.02, Cowlitz, WA)                   ...  ...       None  99999   
2  2 (Tract 21, Cowlitz, WA)                     ...  ...       None  99999   
3  1 (Tract 10, Cowlitz, WA)                     ...  ...       None  99999   
4  1 (Tract 3, Cowlitz, WA)                      ...  ...       None  99999   
5  1 (Tract 3, Cowlitz, WA)                      ...  ...       None  99999   
6  1 (Tract 3, Cowlitz, WA)                      ...  ...       None  99999   
7  1 (Tract 7.03, Cowlitz, WA)                   ...  ...       None  99999   
8  2 (Tract 12, Cowlitz, WA)                     ...  ...       None  99999   
9  6 (Tract 8, Cowlitz, WA)                      ...  ...       None  99999   

  nectname   mil milname     stwib  \
0     None  None    None  53000007   
1     None  None    None  53000007   
2     None  None    None  53000007   
3     None  None    None  53000007   
4     None  None    None  53000007   
5     None  None    None  53000007   
6     None  None    None  53000007   
7     None  None    None  53000007   
8     None  None    None  53000007   
9     None  None    None  53000007   

                                           stwibname   blklatdd    blklondd  \
0  07 Southwest Washington WIB                   ..

In [7]:
pd.read_sql("SELECT stschoolname, stschool FROM wa_geo_xwalk LIMIT 10;", conn)

stschoolname stschool
0  Longview Public Schools, WA                   ...  5304470
1  Longview Public Schools, WA                   ...  5304470
2  Longview Public Schools, WA                   ...  5304470
3  Kelso School District, WA                     ...  5300003
4  Longview Public Schools, WA                   ...  5304470
5  Longview Public Schools, WA                   ...  5304470
6  Longview Public Schools, WA                   ...  5304470
7  Longview Public Schools, WA                   ...  5304470
8  Kelso School District, WA                     ...  5300003
9  Longview Public Schools, WA                   ...  5304470

In [8]:
ct_puma_xwalk = pd.read_sql('SELECT * FROM ct_puma_xwalk LIMIT 10;', conn)
print(print(pd.read_sql("SELECT COUNT(*) FROM ct_puma_xwalk;", conn)))
ct_puma_xwalk

   count
0  74091
None


statefp countyfp tractce puma5ce
0      01      001  020100   02100
1      01      001  020200   02100
2      01      001  020300   02100
3      01      001  020400   02100
4      01      001  020500   02100
5      01      001  020600   02100
6      01      001  020700   02100
7      01      001  020801   02100
8      01      001  020802   02100
9      01      001  020900   02100

In [9]:
pd.read_sql("""SELECT * From ct_puma_xwalk where puma5ce BETWEEN '11610' AND '11615'""", conn)

statefp countyfp tractce puma5ce
0        53      033  025101   11610
1        53      033  025102   11610
2        53      033  025200   11610
3        53      033  025301   11610
4        53      033  025302   11610
..      ...      ...     ...     ...
139      53      033  032007   11615
140      53      033  032008   11615
141      53      033  032010   11615
142      53      033  032011   11615
143      53      033  032102   11615

[144 rows x 4 columns]

### ALL PUMAs IN WASHINGTON STATE

In [10]:
pd.read_sql("SELECT * FROM puma_names_2010 WHERE state_name = 'Washington' ;", conn)

state_fips                                         state_name cpuma0010  \
0          53  Washington                                    ...      1030   
1          53  Washington                                    ...      1031   
2          53  Washington                                    ...      1032   
3          53  Washington                                    ...      1032   
4          53  Washington                                    ...      1032   
5          53  Washington                                    ...      1032   
6          53  Washington                                    ...      1032   
7          53  Washington                                    ...      1032   
8          53  Washington                                    ...      1032   
9          53  Washington                                    ...      1033   
10         53  Washington                                    ...      1033   
11         53  Washington                                    ...      1033   
12         53  Washington                                    ...      1033   
13         53  Washington                                    ...      1034   
14         53  Washington                                    ...      1034   
15         53  Washington                                    ...      1035   
16         53  Washington                                    ...      1035   
17         53  Washington                                    ...      1035   
18         53  Washington                                    ...      1035   
19         53  Washington                                    ...      1036   
20         53  Washington                                    ...      1036   
21         53  Washington                                    ...      1036   
22         53  Washington                                    ...      1036   
23         53  Washington                                    ...      1037   
24         53  Washington                                    ...      1037   
25         53  Washington                                    ...      1038   
26         53  Washington                                    ...      1038   
27         53  Washington                                    ...      1038   
28         53  Washington                                    ...      1038   
29         53  Washington                                    ...      1038   
30         53  Washington                                    ...      1038   
31         53  Washington                                    ...      1038   
32         53  Washington                                    ...      1039   
33         53  Washington                                    ...      1040   
34         53  Washington                                    ...      1041   
35         53  Washington                                    ...      1042   
36         53  Washington                                    ...      1043   
37         53  Washington                                    ...      1044   
38         53  Washington                                    ...      1044   
39         53  Washington                                    ...      1044   
40         53  Washington                                    ...      1044   
41         53  Washington                                    ...      1044   
42         53  Washington                                    ...      1044   
43         53  Washington                                    ...      1044   
44         53  Washington                                    ...      1044   
45         53  Washington                                    ...      1044   
46         53  Washington                                    ...      1045   
47         53  Washington                                    ...      1046   
48         53  Washington                                    ...      1047   
49         53  Washington                                    ...      1047   
50         53  Washington

PUMAS in South King County:
11615 King County (Southeast)--Maple Valley, Covington, Enumclaw
11614 King County (Southwest)--Auburn City, Lakeland
11613 King County (Southwest Central)--Kent City
11612 King County (Far Southwest)--Federal Way, Des Moines Cities & Vashon Island
11611 King County (West Central)--Burien, SeaTac, Tukwila Cities & White Center PUMA

Maybe?
11609 King County (Central)--Sammamish, Issaquah, Mercer Island & Newcastle Cities PUMA
11610 King County (Central)--Renton City, Fairwood, Bryn Mawr & Skyway PUMA




In [11]:
oypuma10 = pd.read_sql("""SELECT 
                serialno,
                agep,
                pwgtp,
                sex,
                schl,
                puma,
                puma_name
                FROM pums_2017 p2
                JOIN puma_names_2010 pn USING(puma)
                WHERE agep BETWEEN '16' AND '24'
                AND puma BETWEEN '11610' AND '11615'
                AND esr = '3' OR esr = '6'
                AND sch = '1'
                ORDER BY ageP DESC;""", conn)
oypuma10

serialno  agep  pwgtp sex schl   puma  \
0   2014000964654  24.0   12.0   2   21  11610   
1   2013000059060  22.0   19.0   1   17  11610   
2   2013001103945  22.0   27.0   1   16  11610   
3   2016001292070  22.0   59.0   2   18  11610   
4   2017000407899  22.0   19.0   2   18  11610   
5   2017001373291  22.0   14.0   1   16  11610   
6   2014000753355  21.0   22.0   2   16  11610   
7   2015000016530  21.0   45.0   1   17  11610   
8   2014001349122  21.0   29.0   2   16  11610   
9   2015000422539  21.0   17.0   1   16  11610   
10  2017000918811  20.0   48.0   1   16  11610   
11  2013000745367  19.0    7.0   1   16  11610   
12  2013000431365  19.0   18.0   2   16  11610   
13  2014001074786  18.0   99.0   2   18  11610   

                                            puma_name  
0   King County (Central)--Renton City, Fairwood, ...  
1   King County (Central)--Renton City, Fairwood, ...  
2   King County (Central)--Renton City, Fairwood, ...  
3   King County (Central)--Renton City, Fairwood, ...  
4   King County (Central)--Renton City, Fairwood, ...  
5   King County (Central)--Renton City, Fairwood, ...  
6   King County (Central)--Renton City, Fairwood, ...  
7   King County (Central)--Renton City, Fairwood, ...  
8   King County (Central)--Renton City, Fairwood, ...  
9   King County (Central)--Renton City, Fairwood, ...  
10  King County (Central)--Renton City, Fairwood, ...  
11  King County (Central)--Renton City, Fairwood, ...  
12  King County (Central)--Renton City, Fairwood, ...  
13  King County (Central)--Renton City, Fairwood, ...

In [12]:
oypuma11 = pd.read_sql("""SELECT 
                serialno,
                agep,
                pwgtp,
                sex,
                schl,
                puma,
                puma_name
                FROM pums_2017 p2
                JOIN puma_names_2010 pn USING(puma)
                WHERE agep BETWEEN 16 AND 24
                AND puma ='11611'
                AND esr = '3'
                AND sch = '1'
                ORDER BY ageP DESC;""", conn)
oypuma11

serialno  agep  pwgtp sex schl   puma  \
0   2016000874246  24.0   59.0   2   14  11611   
1   2014000498381  24.0   39.0   1   16  11611   
2   2016000286077  24.0   31.0   1   21  11611   
3   2015000325063  24.0   45.0   1   16  11611   
4   2014000495936  23.0   76.0   1   11  11611   
5   2013000640932  23.0   23.0   2   13  11611   
6   2017000128413  23.0   12.0   1   19  11611   
7   2013001142649  23.0    9.0   1   17  11611   
8   2017000828457  22.0   10.0   1   15  11611   
9   2016000947360  22.0   15.0   1   16  11611   
10  2013000057563  21.0   20.0   1   16  11611   
11  2014000551252  21.0   18.0   2   16  11611   
12  2013000599234  20.0    9.0   1   17  11611   
13  2017000813384  20.0   14.0   1   16  11611   
14  2017001014999  20.0   57.0   1   16  11611   
15  2017000384030  19.0   15.0   1   16  11611   
16  2013001071031  18.0   45.0   1   17  11611   
17  2013000360571  18.0   23.0   2   13  11611   
18  2017001295574  17.0   18.0   1   14  11611   

                                            puma_name  
0   King County (West Central)--Burien, SeaTac, Tu...  
1   King County (West Central)--Burien, SeaTac, Tu...  
2   King County (West Central)--Burien, SeaTac, Tu...  
3   King County (West Central)--Burien, SeaTac, Tu...  
4   King County (West Central)--Burien, SeaTac, Tu...  
5   King County (West Central)--Burien, SeaTac, Tu...  
6   King County (West Central)--Burien, SeaTac, Tu...  
7   King County (West Central)--Burien, SeaTac, Tu...  
8   King County (West Central)--Burien, SeaTac, Tu...  
9   King County (West Central)--Burien, SeaTac, Tu...  
10  King County (West Central)--Burien, SeaTac, Tu...  
11  King County (West Central)--Burien, SeaTac, Tu...  
12  King County (West Central)--Burien, SeaTac, Tu...  
13  King County (West Central)--Burien, SeaTac, Tu...  
14  King County (West Central)--Burien, SeaTac, Tu...  
15  King County (West Central)--Burien, SeaTac, Tu...  
16  King County (West Central)--Burien, SeaTac, Tu...  
17  King County (West Central)--Burien, SeaTac, Tu...  
18  King County (West Central)--Burien, SeaTac, Tu...

In [13]:
oypuma12 = pd.read_sql("""SELECT 
                serialno,
                agep,
                pwgtp,
                sex,
                schl,
                puma,
                puma_name
                FROM pums_2017 p2
                JOIN puma_names_2010 pn USING(puma)
                WHERE agep BETWEEN 16 AND 24
                AND puma ='11612'
                AND esr = '3'
                AND sch = '1'
                ORDER BY ageP DESC;""", conn)
oypuma12

serialno  agep  pwgtp sex schl   puma  \
0   2015000288090  24.0   14.0   1   16  11612   
1   2015000895429  24.0   24.0   2   21  11612   
2   2016000474107  23.0  110.0   2   16  11612   
3   2014000261441  23.0   40.0   1   16  11612   
4   2014000261441  23.0   39.0   1   16  11612   
5   2015000522021  23.0   20.0   1   20  11612   
6   2015000354955  23.0   11.0   2   18  11612   
7   2016000443986  22.0   16.0   2   17  11612   
8   2014001162853  22.0   22.0   1   16  11612   
9   2013000464262  22.0   22.0   1   16  11612   
10  2014001475081  22.0   13.0   1   16  11612   
11  2017000751960  22.0   54.0   1   16  11612   
12  2015001030849  22.0   47.0   2   16  11612   
13  2013000330366  21.0   21.0   1   16  11612   
14  2014000598099  21.0   49.0   2   19  11612   
15  2013000388196  21.0   13.0   1   17  11612   
16  2017000806771  20.0   41.0   1   16  11612   
17  2014000434014  20.0   14.0   1   15  11612   
18  2014001475081  20.0   15.0   2   15  11612   
19  2017000616102  19.0   51.0   1   16  11612   
20  2015000664648  19.0   20.0   1   16  11612   
21  2017000360750  18.0   77.0   1   15  11612   
22  2017000353715  18.0   29.0   1   16  11612   

                                            puma_name  
0   King County (Far Southwest)--Federal Way, Des ...  
1   King County (Far Southwest)--Federal Way, Des ...  
2   King County (Far Southwest)--Federal Way, Des ...  
3   King County (Far Southwest)--Federal Way, Des ...  
4   King County (Far Southwest)--Federal Way, Des ...  
5   King County (Far Southwest)--Federal Way, Des ...  
6   King County (Far Southwest)--Federal Way, Des ...  
7   King County (Far Southwest)--Federal Way, Des ...  
8   King County (Far Southwest)--Federal Way, Des ...  
9   King County (Far Southwest)--Federal Way, Des ...  
10  King County (Far Southwest)--Federal Way, Des ...  
11  King County (Far Southwest)--Federal Way, Des ...  
12  King County (Far Southwest)--Federal Way, Des ...  
13  King County (Far Southwest)--Federal Way, Des ...  
14  King County (Far Southwest)--Federal Way, Des ...  
15  King County (Far Southwest)--Federal Way, Des ...  
16  King County (Far Southwest)--Federal Way, Des ...  
17  King County (Far Southwest)--Federal Way, Des ...  
18  King County (Far Southwest)--Federal Way, Des ...  
19  King County (Far Southwest)--Federal Way, Des ...  
20  King County (Far Southwest)--Federal Way, Des ...  
21  King County (Far Southwest)--Federal Way, Des ...  
22  King County (Far Southwest)--Federal Way, Des ...

In [14]:
oypuma13 = pd.read_sql("""SELECT 
                serialno,
                agep,
                pwgtp,
                sex,
                schl,
                puma,
                puma_name
                FROM pums_2017 p2
                JOIN puma_names_2010 pn USING(puma)
                WHERE agep BETWEEN 16 AND 24
                AND puma ='11613'
                AND esr = '3'
                AND sch = '1'
                ORDER BY ageP DESC;""", conn)
oypuma13

serialno  agep  pwgtp sex schl   puma  \
0   2017000736269  24.0   12.0   2   18  11613   
1   2013000950917  24.0   17.0   1   18  11613   
2   2015001241717  23.0   65.0   2   18  11613   
3   2014000716305  23.0   11.0   2   16  11613   
4   2017000371573  23.0   24.0   1   21  11613   
5   2015000566835  22.0   25.0   1   19  11613   
6   2013000798706  22.0   45.0   1   19  11613   
7   2014000347958  22.0   47.0   1   11  11613   
8   2016001307835  22.0   23.0   2   18  11613   
9   2015001455193  22.0   17.0   1   16  11613   
10  2016001334291  22.0   15.0   1   18  11613   
11  2016001443268  22.0   16.0   2   16  11613   
12  2016000572078  20.0   17.0   2   16  11613   
13  2014000261570  20.0   13.0   2   14  11613   
14  2013001375902  20.0   16.0   2   19  11613   
15  2016001395474  19.0   21.0   1   14  11613   
16  2015000436785  19.0   55.0   2   16  11613   
17  2015001220225  19.0   12.0   1   16  11613   
18  2015000413383  18.0   26.0   1   15  11613   
19  2013000100470  18.0   16.0   2   13  11613   
20  2014000095629  18.0   12.0   2   01  11613   

                                            puma_name  
0   King County (Southwest Central)--Kent City    ...  
1   King County (Southwest Central)--Kent City    ...  
2   King County (Southwest Central)--Kent City    ...  
3   King County (Southwest Central)--Kent City    ...  
4   King County (Southwest Central)--Kent City    ...  
5   King County (Southwest Central)--Kent City    ...  
6   King County (Southwest Central)--Kent City    ...  
7   King County (Southwest Central)--Kent City    ...  
8   King County (Southwest Central)--Kent City    ...  
9   King County (Southwest Central)--Kent City    ...  
10  King County (Southwest Central)--Kent City    ...  
11  King County (Southwest Central)--Kent City    ...  
12  King County (Southwest Central)--Kent City    ...  
13  King County (Southwest Central)--Kent City    ...  
14  King County (Southwest Central)--Kent City    ...  
15  King County (Southwest Central)--Kent City    ...  
16  King County (Southwest Central)--Kent City    ...  
17  King County (Southwest Central)--Kent City    ...  
18  King County (Southwest Central)--Kent City    ...  
19  King County (Southwest Central)--Kent City    ...  
20  King County (Southwest Central)--Kent City    ...

In [15]:
oypuma14 = pd.read_sql("""SELECT 
                serialno,
                agep,
                pwgtp,
                sex,
                schl,
                puma,
                puma_name
                FROM pums_2017 p2
                JOIN puma_names_2010 pn USING(puma)
                WHERE agep BETWEEN 16 AND 24
                AND puma ='11614'
                AND esr = '3'
                AND sch = '1'
                ORDER BY ageP DESC;""", conn)
oypuma14

serialno  agep  pwgtp sex schl   puma  \
0   2013001098476  24.0   14.0   1   18  11614   
1   2016001455607  24.0    5.0   1   11  11614   
2   2013001415749  24.0   18.0   1   13  11614   
3   2017000492089  24.0   35.0   2   16  11614   
4   2017000149617  24.0    5.0   2   18  11614   
5   2015000833566  24.0    4.0   1   14  11614   
6   2016000692627  24.0    3.0   2   16  11614   
7   2017000703624  23.0   15.0   2   17  11614   
8   2016001455607  23.0    5.0   1   16  11614   
9   2013001135127  22.0   14.0   2   17  11614   
10  2016001455607  22.0    5.0   1   11  11614   
11  2015000680508  22.0   27.0   1   16  11614   
12  2013001415749  21.0   17.0   1   13  11614   
13  2013001459401  21.0   21.0   1   15  11614   
14  2014001327292  21.0    4.0   1   01  11614   
15  2014001303503  21.0    8.0   1   13  11614   
16  2015001207071  21.0    4.0   2   17  11614   
17  2013000406245  20.0    5.0   1   14  11614   
18  2013001372017  20.0   20.0   1   16  11614   
19  2016000485790  20.0   62.0   2   16  11614   
20  2017001273508  19.0   26.0   1   19  11614   
21  2014000957129  19.0   40.0   2   13  11614   
22  2015000720456  19.0   19.0   1   16  11614   
23  2016000738115  19.0    4.0   1   14  11614   
24  2016001026659  19.0    7.0   1   15  11614   
25  2013000785361  19.0    2.0   2   15  11614   
26  2015000408207  18.0   85.0   1   16  11614   
27  2014001491545  18.0   16.0   2   16  11614   
28  2017000551115  18.0   34.0   1   14  11614   
29  2014001320478  18.0   41.0   2   12  11614   
30  2017000648807  16.0    4.0   1   13  11614   

                                            puma_name  
0   King County (Southwest)--Auburn City & Lakelan...  
1   King County (Southwest)--Auburn City & Lakelan...  
2   King County (Southwest)--Auburn City & Lakelan...  
3   King County (Southwest)--Auburn City & Lakelan...  
4   King County (Southwest)--Auburn City & Lakelan...  
5   King County (Southwest)--Auburn City & Lakelan...  
6   King County (Southwest)--Auburn City & Lakelan...  
7   King County (Southwest)--Auburn City & Lakelan...  
8   King County (Southwest)--Auburn City & Lakelan...  
9   King County (Southwest)--Auburn City & Lakelan...  
10  King County (Southwest)--Auburn City & Lakelan...  
11  King County (Southwest)--Auburn City & Lakelan...  
12  King County (Southwest)--Auburn City & Lakelan...  
13  King County (Southwest)--Auburn City & Lakelan...  
14  King County (Southwest)--Auburn City & Lakelan...  
15  King County (Southwest)--Auburn City & Lakelan...  
16  King County (Southwest)--Auburn City & Lakelan...  
17  King County (Southwest)--Auburn City & Lakelan...  
18  King County (Southwest)--Auburn City & Lakelan...  
19  King County (Southwest)--Auburn City & Lakelan...  
20  King County (Southwest)--Auburn City & Lakelan...  
21  King County (Southwest)--Auburn City & Lakelan...  
22  King County (Southwest)--Auburn City & Lakelan...  
23  King County (Southwest)--Auburn City & Lakelan...  
24  King County (Southwest)--Auburn City & Lakelan...  
25  King County (Southwest)--Auburn City & Lakelan...  
26  King County (Southwest)--Auburn City & Lakelan...  
27  King County (Southwest)--Auburn City & Lakelan...  
28  King County (Southwest)--Auburn City & Lakelan...  
29  King County (Southwest)--Auburn City & Lakelan...  
30  King County (Southwest)--Auburn City & Lakelan...

In [16]:
oypuma15 = pd.read_sql("""SELECT 
                serialno,
                agep,
                pwgtp,
                sex,
                schl,
                puma,
                puma_name
                FROM pums_2017 p2
                JOIN puma_names_2010 pn USING(puma)
                WHERE agep BETWEEN 16 AND 24
                AND puma ='11615'
                AND esr = '3'
                AND sch = '1'
                ORDER BY ageP DESC;""", conn)
oypuma15

serialno  agep  pwgtp sex schl   puma  \
0   2016000650677  24.0   16.0   2   12  11615   
1   2015001265411  24.0   15.0   1   21  11615   
2   2014000329012  24.0   23.0   1   19  11615   
3   2013000067168  24.0   22.0   2   18  11615   
4   2013000564016  24.0   20.0   2   19  11615   
5   2015000488282  24.0   16.0   1   15  11615   
6   2016000183114  24.0   10.0   2   17  11615   
7   2013001310974  23.0   16.0   1   15  11615   
8   2015000122393  23.0   14.0   1   19  11615   
9   2014000312040  23.0   22.0   1   17  11615   
10  2015000691577  23.0   12.0   2   16  11615   
11  2017000826205  22.0   14.0   1   14  11615   
12  2013001096015  22.0   18.0   2   16  11615   
13  2013000220663  22.0   14.0   1   21  11615   
14  2014000329012  22.0   24.0   2   20  11615   
15  2014000664375  22.0   14.0   1   16  11615   
16  2017000004988  21.0   10.0   1   17  11615   
17  2013001059963  21.0   75.0   2   12  11615   
18  2017000106825  20.0   23.0   2   16  11615   
19  2017000933828  19.0    6.0   2   16  11615   
20  2014001346221  19.0   14.0   1   16  11615   
21  2014001411193  19.0   16.0   2   16  11615   

                                            puma_name  
0   King County (Southeast)--Maple Valley, Covingt...  
1   King County (Southeast)--Maple Valley, Covingt...  
2   King County (Southeast)--Maple Valley, Covingt...  
3   King County (Southeast)--Maple Valley, Covingt...  
4   King County (Southeast)--Maple Valley, Covingt...  
5   King County (Southeast)--Maple Valley, Covingt...  
6   King County (Southeast)--Maple Valley, Covingt...  
7   King County (Southeast)--Maple Valley, Covingt...  
8   King County (Southeast)--Maple Valley, Covingt...  
9   King County (Southeast)--Maple Valley, Covingt...  
10  King County (Southeast)--Maple Valley, Covingt...  
11  King County (Southeast)--Maple Valley, Covingt...  
12  King County (Southeast)--Maple Valley, Covingt...  
13  King County (Southeast)--Maple Valley, Covingt...  
14  King County (Southeast)--Maple Valley, Covingt...  
15  King County (Southeast)--Maple Valley, Covingt...  
16  King County (Southeast)--Maple Valley, Covingt...  
17  King County (Southeast)--Maple Valley, Covingt...  
18  King County (Southeast)--Maple Valley, Covingt...  
19  King County (Southeast)--Maple Valley, Covingt...  
20  King County (Southeast)--Maple Valley, Covingt...  
21  King County (Southeast)--Maple Valley, Covingt...

Now that we have the values 

In [17]:
pd.read_sql("""SELECT 
                (SUM(pwgtp) * 20) oy_youths, puma
                FROM pums_2017 p2
                WHERE agep BETWEEN 16 AND 24
                AND puma between '11610' and '11615'
                AND esr = '3'
                AND sch = '1'
                group by puma;""", conn)

oy_youths   puma
0     8700.0  11610
1    10760.0  11611
2    15240.0  11612
3    10100.0  11613
4    11380.0  11614
5     8280.0  11615